spring: 
  application:
    name: project-cal
  datasource:
    url: jdbc:mysql://localhost:3306/himedia?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: himedia
    password: himedia
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE