spring:
  application:
    name: project_cal
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/himedia
    username: himedia
    password: himedia
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    session:
      cookie:
        name: PROJECTCAL_SESSIONID
      timeout: 20m # 세션 유효 시간 설정
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/, classpath:/resources/, classpath:/META-INF/resources/, file:src/main/webapp/