spring:
  application:
    name: project_cal
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://138.2.119.233:3306/project01
    username: project01
    password: 7e0f51dbca86c4d8f8bdc38bd3503b883f84e3fb120d93f6aeaf885033c4a6f4
  #스프링 시큐리티 설정
  security:
     user:
       name: user
       password: 1234
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/, classpath:/resources/, classpath:/META-INF/resources/, file:src/main/webapp/
server:
  servlet:
    session:
      cookie:
        name: PROJECTCAL_SESSIONID
      timeout: 20m # 세션 유효 시간 설정
file:
  upload-dir: /uploads
  # 이메일로 토큰 보내기
  mail:
    host: smtp.example.com  # 이 값을 사용하려는 이메일 서버의 호스트로 변경
    port: 587  # 대부분의 SMTP 서버는 이 포트를 사용
    username: ${email}  # 환경 변수로 설정된 이메일 주소
    password: ${userPassword}  # 환경 변수로 설정된 이메일 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true  # TLS를 사용하는 경우
      mail.smtp.ssl.trust: smtp.example.com  # 사용하는 이메일 서버의 호스트로 변경

  redis:
    host: localhost
    port: 6379