spring:
  application:
    name: project_cal
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://138.2.119.233:3306/project01
    username: project01
    password: 7e0f51dbca86c4d8f8bdc38bd3503b883f84e3fb120d93f6aeaf885033c4a6f4
  #멀티파트를 위한 설정
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 50MB
        location: c:\\uploads

  #스프링 시큐리티 설정
  security:
     user:
       name: user
       password: 1234
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/, classpath:/resources/, classpath:/META-INF/resources/, file:src/main/webapp/
server:
  servlet:
    session:
      cookie:
        name: PROJECTCAL_SESSIONID
      timeout: 20m # 세션 유효 시간 설정

# 파일 경로 바꾸려면 util 클래스의 FilesUtility에서 확인
file:
  upload-dir: /uploads